# Use of `relative_permalinks` ensures post links from the index work properly.
relative_permalinks: true
permalink:     http://colombore.org/:title
baseurl : /colombore.org
url : http://colombore.org


# Setup
title:               colombore
tagline:             'A design text: from and beyond Colombo'
description:         'Colombore is a blog focusing on personal opinions, experiences, ideas and occasional interviews or discussions of a few designers from Colombo, Sri Lanka.'
paginate:            5
